[package]
name = "kwass"
version = "0.1.0"
authors = ["Dawid J. Kubis <dawid.kubis3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.4"
structopt = "0.3.9"
anyhow = "1.0.26"
